main/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index),
    path('post/<int:id>/clone/', views.clone_post),
    path('post/<int:id>/delete/', views.delete_post),
    path('admin/', admin.site.urls),
]

main/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth import get_user_model
from model_utils.models import TimeStampedModel
from .clone_object import clone_object

User = get_user_model()


class Post(TimeStampedModel):
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(_('Title'), max_length=200)
    content = models.TextField(_('Content'))

    def __str__(self):
        return super().__str__() + \
            ' (by %s) "%s": %s' % (self.author, self.title, self.content)


class Comment(TimeStampedModel):
    author = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField(_('Comment'))

    def __str__(self):
        try:
            bookmarked = self.comment_attribute.is_bookmark
        except Exception as e:
            bookmarked = False
        return super().__str__() + \
            ' (by %s) [%s] %s' % (self.author, 'X' if bookmarked else ' ', self.comment)


class CommentAttribute(TimeStampedModel):
    comment = models.OneToOneField(Comment, related_name='comment_attribute', on_delete=models.CASCADE)
    is_bookmark = models.BooleanField(default=False)


class PostComment(TimeStampedModel):
    post = models.ForeignKey(Post, related_name='post_comments', on_delete=models.CASCADE)
    comments = models.ManyToManyField(Comment)

main/views.py
import traceback
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils.safestring import mark_safe
from .models import Post
from .clone_object import clone_object


def index(request):
    return render(request, 'index.html', {
        'posts': Post.objects.all().order_by('id')
    })


def delete_post(request, id):
    try:
        post = get_object_or_404(Post, id=id)
        message = '%s <b>deleted</b>' % post
        post.delete()
        messages.info(request, mark_safe(message))
    except Exception as e:
        messages.error(request, str(e))
    return HttpResponseRedirect('/')


def clone_post(request, id):
    try:
        post = get_object_or_404(Post, id=id)
        #new_obj = post.clone()
        clone = clone_object(post)
        message = '%s <b>cloned</b> to %s' % (post, clone)
        messages.info(request, mark_safe(message))
    except Exception as e:
        messages.error(request, str(e))
        messages.error(request, traceback.format_exc())
    return HttpResponseRedirect('/')

main/templates/index.html
<h1>Posts</h1>

{% if messages %}
<div style="border: 1px solid #ccc;">
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>[{{message.tags}}] {{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

{% for post in posts %}
    <ul>
        <li>{{post}} <a href="/post/{{post.id}}/clone/">[CLONE]</a> <a href="/post/{{post.id}}/delete/">[DELETE]</a></li>
        <li>
            <div>comments:</div>
            <ul>
                {% for comment in post.comment_set.all %}
                    <li>{{ comment }}</li>
                {% endfor %}
            </ul>
        </li>
        <li>
            <div>post comments:</div>
            <ul>
                {% for post_comment in post.post_comments.all %}
                    <div>{{post_comment}}:</div>
                    <ul>
                        {% for comment in post_comment.comments.all %}
                            <li>{{comment}}</li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </ul>
        </li>
    </ul>
    <hr />
{% endfor %}